### PR TITLE
remove duplicate object resources for MEMORY_LIMIT in template json

### PR DESCRIPTION
**Pull request by djbrown**
remove duplicate object with path: objects[4].spec.template.spec.containers[0].resources

### CODE REVIEW

**Comment by djbrown** [comment]
@phracek

**Comment by phracek** [comment]
@djbrown Hi Daniel, thanks for the PR!. I have reviewed the Pull Request but I say, MEMORY_LIMIT is defined once in the parameters section and containers[0].resources used it. Why do you want to remove it? Where is a duplicate?

**Comment by djbrown** [comment]
@phracek resources.limits.memory is specified on L197-L201 and L204-L208

**Review by phracek — APPROVED** [review]
I got it. Thanks. LGTM.

**Comment by phracek** [comment]
@hhorak @pkubatrh @bparees From my point of view it LGTM. I don't have access to merge it :( PTAL as well.

**Pull request merged**
